services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: krishanbhargav150_db_user
      MONGO_INITDB_ROOT_PASSWORD: ePdI32g33Vfo7sY6

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: xekfqlmp
      RABBITMQ_DEFAULT_PASS: WIz_7DpAXZj5faY2rytZh1axR3ufs2GI

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  nps:
    build: ./nps
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb+srv://krishanbhargav150_db_user:ePdI32g33Vfo7sY6@cluster0.u7eyibv.mongodb.net/?appName=Cluster0
      RABBITMQ_URL: amqps://xekfqlmp:WIz_7DpAXZj5faY2rytZh1axR3ufs2GI@gerbil.rmq.cloudamqp.com/xekfqlmp
      REDIS_URL: redis://default:LJIBSHAzK8ckHULWZ9yZczR6aNWWTAIr@redis-12279.crce281.ap-south-1-3.ec2.cloud.redislabs.com:12279
    depends_on:
      - mongodb
      - rabbitmq
      - redis

volumes:
  mongodb_data:
  redis_data: